### ISSUE TITLE
使用ライブラリに関連するエラー（DraggableCore）あり

### ISSUE THREAD

**Issue by yoko-at-home** [yoko-at-home/qin_bulletin-board#1]
Consoleに次のエラーが表示される
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at DraggableCore (http://localhost:3000/static/js/vendors~main.chunk.js:52343:5)
    at Draggable (http://localhost:3000/static/js/vendors~main.chunk.js:51664:5)
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:192:81)
```

**Comment by yoko-at-home** [comment]
これ参考になりそう
https://github.com/react-grid-layout/react-draggable/blob/v4.4.2/lib/DraggableCore.js#L159-L171

**Comment by yoko-at-home** [comment]
この情報を反映したらエラー消えました。
https://github.com/react-grid-layout/react-draggable/blob/v4.4.2/lib/DraggableCore.js#L159-L171
